site_name: The Java Design Patterns Manual
site_url: https://javadesignpatterns.com
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.instant
    - header.autohide
    - announce.dismiss

nav:
  - Home: index.md
  - Catalog:
      - Overview: catalog/index.md
      - Creational Patterns:
          - Singleton Pattern: catalog/creational-patterns/singleton-pattern.md
          - Builder Pattern: catalog/creational-patterns/builder-pattern.md
          - Abstract Factory Pattern: catalog/creational-patterns/abstract-factory-pattern.md
          - Factory Method Pattern: catalog/creational-patterns/factory-method-pattern.md
          - Prototype Pattern: catalog/creational-patterns/prototype-pattern.md
      - Structural Patterns:
          - FaÃ§ade Pattern: catalog/structural-patterns/facade-pattern.md
          - Adapter Pattern: catalog/structural-patterns/adapter-pattern.md
          - Composite Pattern: catalog/structural-patterns/composite-pattern.md
          - Proxy Pattern: catalog/structural-patterns/proxy-pattern.md
          - Flyweight Pattern: catalog/structural-patterns/flyweight-pattern.md
          - Bridge Pattern: catalog/structural-patterns/bridge-pattern.md
          - Decorator Pattern: catalog/structural-patterns/decorator-pattern.md
      - Behavioral Patterns:
          - Chain of responsibility Pattern: catalog/behavioral-patterns/chain-of-responsibility-pattern.md
          - Command Pattern: catalog/behavioral-patterns/command-pattern.md
          - Interpreter Pattern: catalog/behavioral-patterns/interpreter-pattern.md
          - Iterator Pattern: catalog/behavioral-patterns/iterator-pattern.md
          - Mediator Pattern: catalog/behavioral-patterns/mediator-pattern.md
          - Memento Pattern: catalog/behavioral-patterns/memento-pattern.md
          - Observer Pattern: catalog/behavioral-patterns/observer-pattern.md
          - State Pattern: catalog/behavioral-patterns/state-pattern.md
          - Strategy Pattern: catalog/behavioral-patterns/strategy-pattern.md
          - Template Method Pattern: catalog/behavioral-patterns/template-method-pattern.md
          - Visitor Pattern: catalog/behavioral-patterns/visitor-pattern.md
      - Other Patterns:
          - Lazy Initialization Pattern: catalog/other/lazy-initialization-pattern.md
          - Module Pattern: catalog/other/module-pattern.md
          - Null Object Pattern: catalog/other/null-object-pattern.md
          - Object Pool Pattern: catalog/other/object pool-pattern.md




  - Blog:
      - blog/index.md
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - def_list
  - tables
  - md_in_html
  - toc:
      permalink: "#"
plugins:
  - blog:
      blog_toc: true
      post_url_format: "{file}"
      post_readtime: true
      categories: true
      post_excerpt: required
  - search
  - material-plausible
extra:
  analytics:
    provider: plausible
    src: https://plausible.io/js/script.outbound-links.js
    domain: javadesignpatterns.com
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: good
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: bad
          note: >-
            Thanks for your feedback! Help us improve this page by signing up for our <a href="https://nas.io/javanaut" target="_blank" rel="noopener">community</a>.
            
            
